I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/victor_text.rpy", line 64, in script
    show Victor Thinking
Exception: Sayer 'You' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/victor_text.rpy", line 64, in script
    show Victor Thinking
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'You' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
Your First Hackathon 1.0
Sat Feb 20 18:49:30 2021
